7.x islandora 1728
Islandora/islandora_pathauto pull request #25
Opened 2017-01-09 14:02 UTC by nhart

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1728

# What does this Pull Request do?
Prevents Pathauto from creating many useless aliases for objects in the repository but inaccessible from the Islandora site.

# What's new?
Checks if objects are in an accessible namespace before querying and creating each alias.

# How should this be tested?
Create objects in multiple namespaces and limit your site to exclude some; then create patterns for Islandora objects (admin/config/search/path/patterns) and apply them using Pathauto's Bulk Update (admin/config/search/path/update_bulk).
Before: you get aliases for the inaccessible objects.
After: you only get aliases for the accessible ones.

# Additional Notes:
* Does this change require documentation to be updated?  No
* Does this change add any new dependencies? No
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No
* Could this change impact execution of existing code? No

# Interested parties
@rosiel

2017-01-09 14:03 UTC, nhart commented
@rosiel this PR supersedes https://github.com/Islandora/islandora_pathauto/pull/20

2017-01-13 17:01 UTC, rosiel commented
@nhart  this PR seems to include your commits from ISLANDORA-1851 (#24). I therefore don't want to merge this first.

2017-01-13 17:20 UTC, nhart commented
@rosiel correct, I had to make a branch off of my 7.x-ISLANDORA-1851 because the 7.x branch wouldn't be applicable.  Please review and merge #24 first.

2017-02-16 16:13 UTC, DiegoPino commented
@nhart @rosiel #24 is merged. 
Not to this one: What is the status?
There is a  that requires probably rebasing. 
Is this one required to close https://jira.duraspace.org/browse/ISLANDORA-1851? I see this pull request mentioned in both https://jira.duraspace.org/browse/ISLANDORA-1851 and https://jira.duraspace.org/browse/ISLANDORA-1728
Ping me if you need help. Thanks!

2017-02-16 20:03 UTC, nhart commented
I closed this by mistake :(

2017-02-16 20:11 UTC, nhart commented
I re-based and fixed conflicts. @rosiel @DiegoPino

2017-02-16 21:32 UTC, DiegoPino commented
@nhart review coming soon. No expert on this module but will give the logic a view. Will need @rosiel expert eye on this one(the bulk part). Thanks a lot!

2017-02-21 18:06 UTC, DiegoPino requested changes
Would prefer the easier to follow filter for namespace restrictions already in use in collection display.

2017-02-21 18:06 UTC, DiegoPino commented on islandora_pathauto.module
> +    if (variable_get('islandora_namespace_restriction_enforced', FALSE)) {
The logic seems a lot more complex than the one already tested and proved working at `function islandora_islandora_basic_collection_get_query_filters()` which  goes like this 
```PHP 
$enforced = variable_get('islandora_namespace_restriction_enforced', FALSE);
  if ($enforced) {
    $namespace_array = islandora_get_allowed_namespaces();
    $namespace_sparql = implode('|', $namespace_array);
    return array('islandora_namespace_restrictions' => format_string('regex(str(?object), "info:fedora/(!namespaces):")', array('!namespaces' => $namespace_sparql)));
  }
````
Any reason for go for this way instead?

2017-02-21 18:30 UTC, nhart commented on islandora_pathauto.module
> +    if (variable_get('islandora_namespace_restriction_enforced', FALSE)) {
Copy and paste from another module. I can make it less complicated if you think it's required.

2017-02-27 14:19 UTC, DiegoPino commented on islandora_pathauto.module
> +    if (variable_get('islandora_namespace_restriction_enforced', FALSE)) {
@nhart could you update this part of the code so we can get this into the release?I really would prefer that implementation I referenced. I think we will need to make a project wide check on namespace restrictions probably in the future, and makes sense to have if not a common function, at least the same implementation everywhere to  make searching and debugging easier. thanks a lot!!

2017-03-01 13:24 UTC, DiegoPino commented
@nhart thanks! Let me check this quickly during the morning, Travis still has some issues, will restart that Job and will then Merge. You are great!

2017-03-01 15:32 UTC, rosiel approved these changes
Looks good!

2017-03-01 15:33 UTC, rosiel commented on islandora_pathauto.module
> +    if (variable_get('islandora_namespace_restriction_enforced', FALSE)) {
@DiegoPino  - it seems you have to change this review from "requested changes"? (still getting used to this github review business)

2017-03-01 15:34 UTC, DiegoPino approved these changes

2017-03-01 15:36 UTC, DiegoPino commented
@nhart cool. @rosiel if you could make the honors and merge 😃

2017-03-01 16:31 UTC, rosiel commented
Ran the code through to ensure it runs and honours namespace restrictions. Success. Merging!

2017-03-01 16:31 UTC, merged

2017-03-01 16:42 UTC, DiegoPino commented
One additional improvement for this release! Thanks @nhart and @rosiel for your work here.